# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def login(self):
    self.driver.get("https://organicafoods.odoo.com/web")
    WebDriverWait(self.driver,50).until(expected_conditions.presence_of_element_located((By.ID, "login")))
    self.driver.find_element(By.ID, "login").click()
    # 7 | type | id=login | gm070797@gmail.com | 
    self.driver.find_element(By.ID, "login").send_keys("gm070797@gmail.com")
    # 8 | type | id=password | Organicafoods | 
    self.driver.find_element(By.ID, "password").send_keys("Organicafoods")
    # 9 | click | css=.btn |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    WebDriverWait(self.driver,50).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".o_app:nth-child(2) > .o_app_icon")))
    self.driver.find_element(By.CSS_SELECTOR, ".o_app:nth-child(2) > .o_app_icon").click()
    # 4 | click | css=div.o_kanban_record:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > button:nth-child(1) |  | 
    WebDriverWait(self.driver,50).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "div.o_kanban_record:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > button:nth-child(1)")))
    self.driver.find_element(By.CSS_SELECTOR, "div.o_kanban_record:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > button:nth-child(1)").click()
  
  def test_deselectcustomer(self):
    # Test name: deselect customer
    # Step # | name | target | value | comment
    self.test_selectcustomer()
    # 5 | click | css=.set-customer |  | 
    WebDriverWait(self.driver,50).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".set-customer")))
    self.driver.find_element(By.CSS_SELECTOR, ".set-customer").click()
    # 6 | click | css=.next:nth-child(5) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".next:nth-child(5)").click()
  
  def test_choosepaymentmethod(self):
    # Test name: choose payment method
    # Step # | name | target | value | comment
    self.login()
    WebDriverWait(self.driver,100).until(expected_conditions.invisibility_of_element_located((By.CLASS_NAME,"loader"))) 
    WebDriverWait(self.driver,50).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".product:nth-child(1) img")))
    # 5 | click | css=.product:nth-child(1) img |  | 
    WebDriverWait(self.driver,100).until(expected_conditions.invisibility_of_element_located((By.CLASS_NAME, "loader")))
    self.driver.find_element(By.CSS_SELECTOR, ".product:nth-child(1) img").click()
    # 6 | click | css=.fa-chevron-right |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa-chevron-right").click()
    # 7 | click | css=.paymentmethod:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".paymentmethod:nth-child(1)").click()
  
  def test_adddiscount(self):
    # Test name: add_discount
    # Step # | name | target | value | comment
    self.login()
    WebDriverWait(self.driver,100).until(expected_conditions.invisibility_of_element_located((By.CLASS_NAME,"loader")))
    # 5 | click | css=.product:nth-child(1) img |  | 
    WebDriverWait(self.driver,50).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".product:nth-child(1) img")))
    WebDriverWait(self.driver,100).until(expected_conditions.invisibility_of_element_located((By.CLASS_NAME, "loader")))
    self.driver.find_element(By.CSS_SELECTOR, ".product:nth-child(1) img").click()
    # 6 | click | css=.numpad:nth-child(3) > .mode-button:nth-child(9) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".numpad:nth-child(3) > .mode-button:nth-child(9)").click()
    # 7 | click | css=.numpad:nth-child(3) > .input-button:nth-child(1) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".numpad:nth-child(3) > .input-button:nth-child(1)").click()
    # 8 | click | css=.numpad:nth-child(3) > .input-button:nth-child(2) |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".numpad:nth-child(3) > .input-button:nth-child(2)").click()
  
  def test_searchproduct(self):
    # Test name: search_product
    # Step # | name | target | value | comment
    self.login()
    # 5 | click | css=.rightpane-header input |  | 
    WebDriverWait(self.driver,100).until(expected_conditions.invisibility_of_element_located((By.CLASS_NAME,"loader")))
    WebDriverWait(self.driver, 50).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".rightpane-header input")))
    WebDriverWait(self.driver,100).until(expected_conditions.invisibility_of_element_located((By.CLASS_NAME, "loader")))
    self.driver.find_element(By.CSS_SELECTOR, ".rightpane-header input").click()
    # 6 | type | css=.rightpane-header input | graphic | 
    self.driver.find_element(By.CSS_SELECTOR, ".rightpane-header input").send_keys("graphic")
  
  def test_selectcustomer(self):
    # Test name: select customer
    # Step # | name | target | value | comment
    self.login()
    WebDriverWait(self.driver,100).until(expected_conditions.invisibility_of_element_located((By.CLASS_NAME,"loader")))
    # 5 | click | css=.set-customer |  | 
    WebDriverWait(self.driver,100).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".set-customer")))
    WebDriverWait(self.driver,100).until(expected_conditions.invisibility_of_element_located((By.CLASS_NAME, "loader")))
    self.driver.find_element(By.CSS_SELECTOR, ".set-customer").click()
    # 6 | click | css=.client-line:nth-child(1) > td:nth-child(1) |  | 
    WebDriverWait(self.driver,50).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".client-line:nth-child(1) > td:nth-child(1)")))
    self.driver.find_element(By.CSS_SELECTOR, ".client-line:nth-child(1) > td:nth-child(1)").click()
    # 7 | click | css=.next:nth-child(5) |  | 
    WebDriverWait(self.driver,50).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".next:nth-child(5)")))
    self.driver.find_element(By.CSS_SELECTOR, ".next:nth-child(5)").click()
  
