# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC

class TestPos():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def pos(self):
    self.driver.get("https://organicafoods.odoo.com/web/login")
    self.driver.find_element(By.ID, "login").send_keys("gm070797@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Organicafoods")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    WebDriverWait(self.driver,10).until(EC.presence_of_element_located((By.CSS_SELECTOR,".o_app:nth-child(2) > .o_app_icon")))
    self.driver.find_element(By.CSS_SELECTOR, ".o_app:nth-child(2) > .o_app_icon").click()
  # def test_session_start(self):
  #   self.test_pos()
  #   WebDriverWait(self.driver,10).until(EC.presence_of_element_located((By.CSS_SELECTOR,'o_kanban_record:nth-child(1) .btn'))).click()
  
  
  def test_resume_session(self):
    self.pos()
    WebDriverWait(self.driver,100).until(EC.presence_of_element_located((By.CSS_SELECTOR,'.o_kanban_record:nth-child(1) .btn-primary'))).click()
  # def test_close_session(self):
  #   self.test_resume_session()
  #   WebDriverWait(self.driver,100).until(EC.presence_of_element_located((By.CSS_SELECTOR,'.header-button')))
  #   self.driver.find_element_by_css_selector('.header-button')
  #   self.driver.find_element_by_css_selector('.header-button').click()
  
  
  def test_add_products(self):
    self.test_resume_session()
    WebDriverWait(self.driver,100).until(EC.element_to_be_clickable((By.CSS_SELECTOR,".product:nth-child(1) img")))
    WebDriverWait(self.driver,100).until(EC.invisibility_of_element_located((By.CLASS_NAME,"loader")))
    self.driver.find_element(By.CSS_SELECTOR, ".product:nth-child(1) img").click()
    WebDriverWait(self.driver,100).until(EC.element_to_be_clickable((By.CSS_SELECTOR,".product:nth-child(2) img")))
    WebDriverWait(self.driver,100).until(EC.invisibility_of_element_located((By.CLASS_NAME,"loader")))
    self.driver.find_element(By.CSS_SELECTOR, ".product:nth-child(2) img").click()


  def test_delete_products(self):
    self.test_add_products()
    WebDriverWait(self.driver,100).until(EC.invisibility_of_element_located((By.CLASS_NAME,"loader")))
    self.driver.find_element_by_css_selector('.orderline:nth-child(1)').click()
    # 9 | click | css=.numpad:nth-child(3) > .numpad-backspace |  | del button
    WebDriverWait(self.driver,100).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".numpad:nth-child(3) > .numpad-backspace")))
    self.driver.find_element(By.CSS_SELECTOR, ".numpad:nth-child(3) > .numpad-backspace").click()
    # 10 | click | css=.numpad:nth-child(3) > .numpad-backspace |  | del button
    WebDriverWait(self.driver,100).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".numpad:nth-child(3) > .numpad-backspace")))
    self.driver.find_element(By.CSS_SELECTOR, ".numpad:nth-child(3) > .numpad-backspace").click()
  
  
  def test_add_order(self):
    self.test_resume_session()
    WebDriverWait(self.driver,100).until(EC.presence_of_element_located((By.CSS_SELECTOR,".fa-plus:nth-child(1)")))
    WebDriverWait(self.driver,100).until(EC.invisibility_of_element_located((By.CLASS_NAME,"loader")))
     # 7 | click | css=.fa-plus:nth-child(1) |  | add order
    self.driver.find_element(By.CSS_SELECTOR, ".fa-plus:nth-child(1)").click()
  
  
  def test_remove_order(self):
    self.test_resume_session()
    WebDriverWait(self.driver,100).until(EC.presence_of_element_located((By.CSS_SELECTOR,".fa-plus:nth-child(1)")))
    WebDriverWait(self.driver,100).until(EC.invisibility_of_element_located((By.CLASS_NAME,"loader")))
    # 8 | click | css=.deleteorder-button |  | remove order
    self.driver.find_element(By.CSS_SELECTOR, ".deleteorder-button").click()




